
import React from 'react';
import ScriptGenerator from './components/ScriptGenerator';
import Header from './components/Header';

function App() {
  return (
    <div className="min-h-screen bg-slate-900 text-slate-200 font-sans selection:bg-cyan-300 selection:text-slate-900">
      <main className="container mx-auto px-4 py-8 max-w-4xl">
        <Header />
        <ScriptGenerator />
      </main>
      <footer className="text-center py-4 text-slate-500 text-sm">
        <p>Generated by a world-class senior frontend React engineer.</p>
      </footer>
    </div>
  );
}

export default App;
